# Generated by Django 2.2 on 2020-03-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='received',
            field=models.BooleanField(default=True),
        ),
    ]
