# Generated by Django 2.2 on 2020-04-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200331_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='idSearch',
            field=models.IntegerField(null=True),
        ),
    ]
